### ISSUE TITLE
Parsing error loading recipe blockus:bamboo_barrel

### ISSUE THREAD

**Issue by pandory-network** [Brandcraf06/Blockus#10]
I have a little Error with the blockus:bamboo_barrel
```

> [19:41:00] [Server thread/ERROR]: Parsing error loading recipe blockus:bamboo_barrel
> com.google.gson.JsonSyntaxException: Unknown item 'minecraft:bamboo_planks'
> at net.minecraft.class_1856.method_17873(class_1856.java:162) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at java.util.Optional.orElseThrow(Optional.java:290) ~[?:1.8.0_191]
> at net.minecraft.class_1856.method_8107(class_1856.java:162) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_1856.method_8102(class_1856.java:144) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_1869.method_8157(class_1869.java:225) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_1869.method_8159(class_1869.java:24) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_1869$class_1870.method_8164(class_1869.java:246) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_1869$class_1870.method_8121(class_1869.java:241) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_1863.method_17720(class_1863.java:139) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_1863.method_14491(class_1863.java:61) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_4013.method_18235(class_4013.java:12) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at java.util.concurrent.CompletableFuture.uniRun(CompletableFuture.java:705) ~[?:1.8.0_191]
> at java.util.concurrent.CompletableFuture$UniRun.tryFire(CompletableFuture.java:687) ~[?:1.8.0_191]
> at java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:442) ~[?:1.8.0_191]
> at net.minecraft.class_4014.method_18365(class_4014.java:71) ~[intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_3738.run(class_3738.java:18) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_1255.method_18859(class_1255.java:135) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_4093.method_18859(class_4093.java:23) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_1255.method_16075(class_1255.java:114) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.server.MinecraftServer.method_20415(MinecraftServer.java:702) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.server.MinecraftServer.method_16075(MinecraftServer.java:696) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_1255.method_18857(class_1255.java:123) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.server.MinecraftServer.method_3752(MinecraftServer.java:1466) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.server.MinecraftServer.method_3800(MinecraftServer.java:450) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.server.MinecraftServer.method_3735(MinecraftServer.java:366) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.class_3176.method_3823(class_3176.java:218) [intermediary-minecraft_server_1.14.1.jar:?]
> at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:605) [intermediary-minecraft_server_1.14.1.jar:?]
> at java.lang.Thread.run(Thread.java:748) [?:1.8.0_191]

```

**Comment by Juuxel** [comment]
This is the cause: https://github.com/Brandcraf06/Blockus/blob/9bc8ac633150af3b50e8792297648d2dd9d5c1da/src/main/resources/data/blockus/recipes/bamboo_barrel.json#L9-L16
