### ISSUE TITLE
Promenade Error

### ISSUE THREAD

**Issue by A5ho9999** [Brandcraf06/Blockus#292]
Game crashes on start up.

Fabric 1.20.1
Blockus Version: https://modrinth.com/mod/blockus/version/2.7.1+1.20
Promenade Version: https://modrinth.com/mod/promenade/version/v4.0.0

Similar to #274

```
java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'blockus'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
	at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	Suppressed: java.lang.NoClassDefFoundError: net/minecraft/class_437
		at java.lang.Class.forName0(Native Method) ~[?:?]
		at java.lang.Class.forName(Class.java:488) ~[?:?]
		at java.lang.Class.forName(Class.java:467) ~[?:?]
		at net.fabricmc.loader.impl.util.DefaultLanguageAdapter.create(DefaultLanguageAdapter.java:50) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointStorage$NewEntry.getOrCreate(EntrypointStorage.java:117) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointContainerImpl.getEntrypoint(EntrypointContainerImpl.java:53) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.Hooks.startServer(Hooks.java:62) ~[fabric-loader-0.14.21.jar:?]
		at net.minecraft.server.Main.main(Main.java:112) ~[server-intermediary.jar:?]
		at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotServer.main(KnotServer.java:23) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.server.FabricServerLauncher.main(FabricServerLauncher.java:69) ~[fabric-loader-0.14.21.jar:?]
	Caused by: java.lang.ClassNotFoundException: net.minecraft.class_437
		at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
		at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
		at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
		... 14 more
Caused by: java.lang.NoClassDefFoundError: fr/hugman/promenade/registry/content/PalmContent
	at com.brand.blockus.modcompat.promenade.BlockusPromenadeBlocks.init(BlockusPromenadeBlocks.java:59) ~[blockus-2.7.1+1.20.jar:?]
	at com.brand.blockus.Blockus.onInitialize(Blockus.java:48) ~[blockus-2.7.1+1.20.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 7 more
Caused by: java.lang.ClassNotFoundException: fr.hugman.promenade.registry.content.PalmContent
	at jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.loadClass(KnotClassDelegate.java:226) ~[fabric-loader-0.14.21.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:112) ~[fabric-loader-0.14.21.jar:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:521) ~[?:?]
	at com.brand.blockus.modcompat.promenade.BlockusPromenadeBlocks.init(BlockusPromenadeBlocks.java:59) ~[blockus-2.7.1+1.20.jar:?]
	at com.brand.blockus.Blockus.onInitialize(Blockus.java:48) ~[blockus-2.7.1+1.20.jar:?]
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47) ~[fabric-loader-0.14.21.jar:?]
	... 7 more

**Comment by Brandcraf06** [comment]
Yes, because Blockus 1.20 uses a compat based on an outdated Promenade version. This will be fixes in the next update.

**Comment by A5ho9999** [comment]
Do you have an estimated timeframe for the next update?
